"""empty message

Revision ID: 27f6227ec4b1
Revises: 1376bec8be3f
Create Date: 2020-10-01 10:11:20.324337

"""

# revision identifiers, used by Alembic.
revision = '27f6227ec4b1'
down_revision = '1376bec8be3f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    ### end Alembic commands ###
